# ansible-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: priyam930/ansible:latest
        command: ["sleep", "infinity"]
